[programs.localnet]
wolftrack = "9uCnxtqvRhMH4YPhAGKDyBmhHkG4Ef3p1YKXdVR7d6Qc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha"
[toolchain]
anchor_version = "0.29.0"
