- name: Install AVM (Anchor Version Manager)
  run: |
    curl -sSfL https://raw.githubusercontent.com/project-serum/anchor/avm/install.sh | sh
    echo "$HOME/.avm/bin" >> $GITHUB_PATH

- name: Install Anchor 0.29.0
  run: |
    avm install 0.29.0
    avm use 0.29.0

- name: Anchor Build
  run: anchor build
