name: Anchor Build

on:
  push:
    paths:
      - '**/*.rs'
      - 'Anchor.toml'
  pull_request:
    paths:
      - '**/*.rs'
      - 'Anchor.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install AVM (Anchor Version Manager)
        run: |
          curl -sSf https://raw.githubusercontent.com/project-serum/anchor/avm/install.sh | sh
          echo "$HOME/.avm/bin" >> $GITHUB_PATH

      - name: Install Anchor 0.29.0
        run: |
          set -e
          source "$HOME/.avm/bin/avm.sh"
          avm install 0.29.0
          avm use 0.29.0
          anchor --version

      - name: Build Anchor project
        run: |
          set -e
          source "$HOME/.avm/bin/avm.sh"
          anchor build
